package exceptiontest;
/*
 * try-catch-finally 模型
 */

import org.junit.Test;

public class ExceptionTest1 {
	@Test
	public void Test1() {
//		String[] str = new String[] {"a","b","c"};
		String str = "123";
//		System.out.println(str[0]);
		str = "abc";
		int num = Integer.parseInt(str);
		
		
	}
	
	
}
